import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./styles/globals.scss";
import Navbar from "@/app/components/layout/navbar/navbar";

const geistNoto = Noto_Sans_Thai({
  variable: "--font-Noto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistNoto.variable} `}>
        <main className="layout-content">{children}</main>
      </body>
    </html>
  );
}
